### PR TITLE
Repository name validation support for templating

### LINKED ISSUE #90: ApplicationSets with templated repository URLs not supported when providing `--repo` or REPO
When having an ApplicationSet with a repository specification that looks like the following:
```
- repoURL: git@github.com:my-org/my-repo-{{.metadata.annotations.repo}}-overrides.git
   targetRevision: my-base-branch
```

When trying to provide that repository format to the tool with `--repo`, the following error occurs:
```
[2025-01-06T17:34:18Z ERROR argocd_diff_preview] ❌ Invalid repository format. Please use OWNER/REPO
[2025-01-06T17:34:18Z DEBUG argocd_diff_preview::utils] Running shell command: which kind
[2025-01-06T17:34:18Z DEBUG argocd_diff_preview::utils] Running shell command: which kind
[2025-01-06T17:34:18Z ERROR argocd_diff_preview] ❌ Invalid repository format
Error: "Invalid repository format"
```

We'd need the tool to be able to update the specific repo entries that have `my-org/my-repo-{{.metadata.annotations.repo}}-overrides.git` in the ApplicationSet in order to make it work for our use case.

Thanks!

### PR DESCRIPTION
**Pull request by dedri-github**
Added support for additional characters in repository names, to allow repository name templating in ApplicationSets: { } and a dot.

Fixes #90

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -198,7 +198,7 @@ async fn run() -> Result<(), Box<dyn Error>> {
 
     let cluster_tool = &opt.local_cluster_tool;
 
-    let repo_regex = Regex::new(r"^[a-zA-Z0-9-]+/[a-zA-Z0-9\._-]+$")?;
+    let repo_regex = Regex::new(r"^[a-zA-Z0-9\._\-\{\}]+/[a-zA-Z0-9\._\-\{\}]+$")?;
```
Comment (dag-andersen) [inline src/main.rs:201]: Thank you for the contribution! 

a _tiny_ bit prettier 🚀 
```suggestion
    let repo_regex = Regex::new(r"^[a-zA-Z0-9\.\{\}_-]+/[a-zA-Z0-9\.\{\}_-]+$")?;
```

**Comment by dedri-github** [comment]
Thanks @dag-andersen, I updated the commit with your suggestion.
